We can combine multiple arrays joining them into one array using:

np.concatenate() Join a sequence of arrays along an existing axis (rows or columns).

Parameters:
1. A sequence of arrays to concatenate. The arrays must have the same shape, except in the dimension corresponding to axis (rows by default). This means that there can be different numbers of rows, but all of the arrays must have the same number of columns.
2. axis : int, optional. The axis along which the arrays will be joined. Default is 0 (rows). 1 selects columns.

In [1]:
import numpy as np
# example of concatenation one-dimensional arrays

a1 = np.array([-1,-2,-3])
a2 = np.array([3,2,1])
a3 = np.array([4,5,6])

# remenber you can concatenate more than 2 arrays
np.concatenate([a1,a2,a3])

array([-1, -2, -3,  3,  2,  1,  4,  5,  6])

In [3]:
# example of concatenation two-dimensional arrays
matrix = np.array([[1,2,3],[4,5,6]])
print('matrix: \n', matrix)
np.concatenate([matrix,matrix])
# by default in axis 0(rows)

matrix: 
 [[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [5]:
# Example of concatenate in axis 1(columns)
matrix = np.array([[1,2,3],[4,5,6]])
print('matrix = \n',matrix)
np.concatenate([matrix,matrix],axis=1)

matrix = 
 [[1 2 3]
 [4 5 6]]


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [6]:
# dimensions MUST match other than the dimension being joined
# v1 only has 2 columns, can't join on rows

v1 = np.array([[1,2],[3,4]])
marix = np.array([[4,5,6],[7,8,9]])
np.concatenate([matrix,v1])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [10]:
# But you could concatenate on columns (both v1 and matrix have two rows)
np.concatenate([matrix, v1],axis=1)

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4]])

np.vstack() Stack arrays in sequence vertically (row wise). 

Parameters:
Arrays to concatenate. 

The arrays must have the same shape along all but the first axis (rows). 1D arrays must have the same length.

In [11]:
# example of np.vstack(vertical or row)
v1 = np.array([1,2,3])
matrix = np.array([[4,5,6],[7,8,9]])
np.vstack([v1,matrix])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.hstack() Stack arrays in sequence horizontally (column wise). 

Parameters
Arrays to concatenate. 

The arrays must have the same shape along all but the second axis (columns), except 1D arrays which can be any length.

In [12]:
# example of np.hstack(horizontal or columns)

matrix = np.array([[4,5,6],[7,8,9]])
print('matrix = \n',matrix)

h1 = np.array([[-1],[-2]])
print('h1 = \n', h1)

np.hstack([h1,matrix])

matrix = 
 [[4 5 6]
 [7 8 9]]
h1 = 
 [[-1]
 [-2]]


array([[-1,  4,  5,  6],
       [-2,  7,  8,  9]])