You can also split an array into several arrays using:

np.split(): Split an array into multiple sub-arrays. 

Parameters:
Array to be divided into sub-arrays

Indices or sections : int or one-dimensional array.
1. If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis.
2. If indices_or_sections is an array, each number in the array indicates where the next section ends.
3. If such a split is not possible, an error is raised.

In [1]:
import numpy as np

# example of np.split of one-dimensional array into 4 equal sized arrays

vec = np.arange(4)
print('vec = ',vec)

v1,v2,v3,v4 = np.split(vec,4)
print('v1 = ',v1)
print('v2 = ',v2)
print('v3 = ',v3)
print('v4 = ',v4)

vec =  [0 1 2 3]
v1 =  [0]
v2 =  [1]
v3 =  [2]
v4 =  [3]


In [2]:

# Change the split from 4 to 3 in your notebook at run it to see what happens.
v1,v2,v3 = np.split(vec,3)
print('v1 = ',v1)
print('v2 = ',v2)
print('v3 = ',v3)

ValueError: array split does not result in an equal division

In [6]:
# example of np.split of one- dimensional array into 3 parts
# rows 0-2, rows 3-4 and rows 5-8
# note [3,5] 
# 3 indicates that the first split ends in index 3
# so this first split includes indexes 0-2
# second split starts at next index,3
# 5 indicates second split ends at index 5
# so the second split will include index 3-4
# when there are no more indexes, whatever is left in the array will end up in the remainder split

vec = np.arange(8)
print('vec = ',vec)


v1,v2,v3 = np.split(vec,[3,5])
print('v1 = ',v1)
print('v2 = ',v2)
print('v3 = ',v3)


vec =  [0 1 2 3 4 5 6 7]
v1 =  [0 1 2]
v2 =  [3 4]
v3 =  [5 6 7]


In [10]:
# Example of np.split in one-dimensional array into 5 parts
vec = np.arange(10.0)
print(vec)

(print(np.split(vec, [3, 5, 6, 10])))
# note that the last array is empty as there are no remaining elements after index 9

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[array([0., 1., 2.]), array([3., 4.]), array([5.]), array([6., 7., 8., 9.]), array([], dtype=float64)]


In [11]:
# example with two dimentional array

# create a two-dimensional array

m1 = np.arange(24).reshape((6,4))
print('m1 = \n',m1)

# split into two equal arrays
mS1,mS2 = np.split(m1,2)

# [2]index for rows,the two first
print('mS1 = \n',mS1)
print('mS2 = \n',mS2)

m1 = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
mS1 = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mS2 = 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [12]:
# Example with two-dimensional array

#Create a two-dimensional array
m1 = np.arange(24).reshape((6, 4))
print("m1 =\n", m1)

# split the first two rows from the rest
mS1,mS2 = np.split(m1,[2])

print("mS1 =\n", mS1)
print("mS2 =\n", mS2)

m1 =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
mS1 =
 [[0 1 2 3]
 [4 5 6 7]]
mS2 =
 [[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [13]:
#You can also use a negative index to indicate the offset from the end of the array 
# rather than the beginning
# split the array, stop at the second row from the end

mS1,mS2 = np.split(m1,[-2])
print("mS1 =\n", mS1)
print("mS2 =\n", mS2)

mS1 =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
mS2 =
 [[16 17 18 19]
 [20 21 22 23]]


np.vsplit()

Array to be divided into sub-arrays
Indexes of sections

In [14]:
# Example of vsplit
# Note the behaviour of vsplit is the same as split( ).
# split optionally takes another argument indicating the axis (row or column) to use
#　The default is row.  vsplit always splits on rows.

print("m1 =\n", m1)

# split the array into two equal sections of rows
above,below = np.vsplit(m1,2)

print("above =\n", above)
print("below =\n", below)

m1 =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
above =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
below =
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [16]:
#Example of vsplit ()
print("m1 =\n", m1)

#split the array into three parts: up to row 2, row 2, rest of array
a,b,c = np.vsplit(m1,np.array([2,3]))

print("a =\n", a)
print("b =\n", b)
print("c =\n", c)

m1 =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a =
 [[0 1 2 3]
 [4 5 6 7]]
b =
 [[ 8  9 10 11]]
c =
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


np.hsplit()

Array to be divided into sub-arrays
Indexes of sections

In [17]:
# example of hsplit()
# hsplit() always split on columns

print('m1 = \n',m1)

# split array into 2 even sections of columns

left,right = np.hsplit(m1,2)
print('left = \n',left)
print('right = \n',right)

m1 = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
left = 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]]
right = 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]


In [20]:
#Example of hsplit ()
print("m1 =\n", m1)

# split array into three parts: up to column 2, column 2 and rest of the array
a,b,c = np.hsplit(m1,np.array([2,3]))
print('a = \n',a)
print('b = \n',b)
print('c = \n',c)

m1 =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a = 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]]
b = 
 [[ 2]
 [ 6]
 [10]
 [14]
 [18]
 [22]]
c = 
 [[ 3]
 [ 7]
 [11]
 [15]
 [19]
 [23]]


In your Jupyter Notebook, write the code that will take the following arrays and slice them to get the desired outputs.

In [21]:
import numpy as np

a1= np.array([[  4,  -8,   7,   4],
              [ 32, -89,  67,   2],
              [ 58, -87,  46,  94]])
print ('a1 = \n',a1)
print('1. = \n', a1[::-1])
print('2. = \n', a1[1:2])
print('3. = \n', a1[:,2:3])
print('4. = \n', a1[1:3,1:3])
print('5. = \n', a1[0:2,2:4])


a1 = 
 [[  4  -8   7   4]
 [ 32 -89  67   2]
 [ 58 -87  46  94]]
1. = 
 [[ 58 -87  46  94]
 [ 32 -89  67   2]
 [  4  -8   7   4]]
2. = 
 [[ 32 -89  67   2]]
3. = 
 [[ 7]
 [67]
 [46]]
4. = 
 [[-89  67]
 [-87  46]]
5. = 
 [[ 7  4]
 [67  2]]


In your Jupyter Notebook write the code that will take arrays (a1, a2, and a3) and concatenate and split them to get the desired outputs.

### 1-dimensional Arrays

In [22]:


a1 = np.arange(20,30)
a2 = np.arange(-20,-10)
a3 = np.arange(10)

#Concatenation 

v1 = np.concatenate([a1, a2, a3])
v2 = np.concatenate([a1[::2],a2[::2]])
v3 = np.concatenate([a1[::-1],a2[::-1], a3[::-1]])
print('v1 = ',v1)
print('v2 = ',v2)
print('v3 =',v3)


v1 =  [ 20  21  22  23  24  25  26  27  28  29 -20 -19 -18 -17 -16 -15 -14 -13
 -12 -11   0   1   2   3   4   5   6   7   8   9]
v2 =  [ 20  22  24  26  28 -20 -18 -16 -14 -12]
v3 = [ 29  28  27  26  25  24  23  22  21  20 -11 -12 -13 -14 -15 -16 -17 -18
 -19 -20   9   8   7   6   5   4   3   2   1   0]


In [23]:

#Split
v1,v2,v3 = np.split(a1,[3,4])
print('v1 = ',v1)
print('v2 = ',v2)
print('v3 = ',v3)

v1 =  [20 21 22]
v2 =  [23]
v3 =  [24 25 26 27 28 29]


### 2-dimensional Arrays

In [24]:
m1 = np.array([[-1, 2, -3],[4, -5, 6],[7, 8, 9]])

#Concatenation
print('====CONCATENATION===')
m2 = np.concatenate([m1,m1[::-1]])
print('m1 = \n', m1)
print('m2 = \n', m2)
m3=np.concatenate([m1,  m1[:3, ::3] ],axis = 1)
print('m3 = \n', m3)



#Split 
print('=====SPLIT=====')
m1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
m2 = np.concatenate([m1,m1[::-1]])
print("m2 =\n", m2)
matrixS1,matrixS2 = np.split(m2,[2]);#[2]index for rows, the two first  
print("matrixS1 =\n", matrixS1)
print("matrixS2 =\n", matrixS2)

====CONCATENATION===
m1 = 
 [[-1  2 -3]
 [ 4 -5  6]
 [ 7  8  9]]
m2 = 
 [[-1  2 -3]
 [ 4 -5  6]
 [ 7  8  9]
 [ 7  8  9]
 [ 4 -5  6]
 [-1  2 -3]]
m3 = 
 [[-1  2 -3 -1]
 [ 4 -5  6  4]
 [ 7  8  9  7]]
=====SPLIT=====
m2 =
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]
 [4 5 6]
 [1 2 3]]
matrixS1 =
 [[1 2 3]
 [4 5 6]]
matrixS2 =
 [[7 8 9]
 [7 8 9]
 [4 5 6]
 [1 2 3]]
