If you recall the functions from the Week 1: Random Numbers, you'll notice that NumPy has the same functions. The main difference is that the NumPy functions will return an array, whereas the Python functions return single values or a list.

In [3]:
import numpy as np
# generate a two-dimensional array with integers numbers
# in this examples a 3*2 array of interger number is generated randomly
# the range of the random number is -4 to 4

r1 = np.random.randint(low = -4, high = 4, size = [3,2])
r1
# Run this code multiple times
# to see the different random values being generated.

array([[-1,  1],
       [ 3, -3],
       [ 2, -2]])

In [4]:
# generate a two- dimensional array with floats
# in this example an array 2*3 of floats numbers is generate randomly

arrayFloat = np.random.rand(2,3)
print('Random float numbers in a range [0 to 1], array 2*3\n',arrayFloat)

Random float numbers in a range [0 to 1], array 2*3
 [[0.69655572 0.4358933  0.8186162 ]
 [0.97535844 0.39024408 0.51430592]]


Like Python random functions, with NumPy you can specify a range from a uniform distribution (each value equally likely).

In [5]:
# generate a two-dimentional array with floats
# In this example an array 4*3 of float number is generate randomly
# Random numbers are in a specific range: -75.5 to 105.5

arrayFloat2 = np.random.uniform(-75.5,105.5,size=(3,3))
print('Random float numbers in a range [-75.5 to 105.5],array 3*3 \n', arrayFloat2)

Random float numbers in a range [-75.5 to 105.5],array 3*3 
 [[ 97.40258667  68.90769724 -68.90415031]
 [ 54.15967981 -30.36318766   6.33191253]
 [-74.57159323   0.10033734   0.75067754]]


In your Jupyter notebook, write code that creates three arrays using the np.zeros, np.random, np.array.  Feel free to choose the number of rows and columns.

 

In [10]:
a1 = np.zeros((3,3))
a2 = np.random.rand(3,5)
a3 = np.array([[1,2,3],[7,8,9]])
print(a1)
print(a2)
print(a3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.1693617  0.15860736 0.35724774 0.10469853 0.72927056]
 [0.43332178 0.16532766 0.25896577 0.84203418 0.76012512]
 [0.48994344 0.59637425 0.66186949 0.97266946 0.40707906]]
[[1 2 3]
 [7 8 9]]
