Sometimes you may need to change the shape of an array you have created. For example, if you add a new column of data. You can do this using the reshape() function. You can also use reshape() to create a 2-dimensional array from 1D data.

The reshape() function takes the number of rows and columns to use for the 2D array.

In [1]:
import numpy as np
# Using re-shape function and arange to create a two-dimensional array from 1D data

# create a 1D array

a1d = np.arange(0,12)
print('a1d before reshape ',a1d)

# reshape data to a 3×4 array
a1d = a1d.reshape(3,4)
print('a1d after reshape \n', a1d)

a1d before reshape  [ 0  1  2  3  4  5  6  7  8  9 10 11]
a1d after reshape 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
# you can also combine the calls into one line
# the arange() is called first,and then reshape() is called on the array returned by arange()
a2d = np.arange(0,15).reshape(3,5)
a2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
# what happen if your one-dimensional array can not fit in your new shape?

a1d = np.arange(0,17).reshape(3,5)

# you can't reshape arrays with different size.
# in this case we have a range of 17 elements
# and the reshape size is 3*5 = 15 elements


ValueError: cannot reshape array of size 17 into shape (3,5)