To access an individual array element, you use square brackets, just like lists. You can also access sub arrays through slicing. Slicing arrays can be useful when you work with large data sets. You can access and process pieces of these data sets without the need to manage all of the data set. This reduces the time needed to do your calculations.

You take a slice of an array with the slice notation, marked by the colon (:) character.

array1[start: stop: step]

start, stop and step have the same behaviour as in the function arange().

Remember if any of these parameters are unspecified, they default to the values start=0, stop=last index, step=1.

Let's start with 1-dimensional array examples.

In [1]:
import numpy as np
# examples of slicing in one-dimensional array in a range with 20 elements starting by zero
a1 = np.arange(20)
# create a one-dimensional array in a range with 20 elements starting by zero
print(a1)

# slice out the first seven elements: stop at index 7, start step have default values
a1[:7]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([0, 1, 2, 3, 4, 5, 6])

In [2]:
# take a slice from the middle of the array
# starting with element at index 5 and stopping at index 15
a1[5:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
# get a slice with every scond element from the array
a1[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
# take a slice with every third element starting at 4
a1[4::3]

array([ 4,  7, 10, 13, 16, 19])

Having a negative step can be confusing, but the effect is that the values for start and stop are swapped. This can convenient when you want to reverse an array.

In [5]:
# reversing all the elements
a1[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [6]:
# revering a part of the array, starting with the element at index 10
a1[10::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])