Multidimensional slices work in the same way as accessing sections of an array, with multiple slices separated by commas. 

In [1]:
import numpy as np
# create a multidimensional array

a2 = np.array([[3, 12, 5, 65],[13, 90, 2, 49], [35, 79, 1, 8]])
a2

array([[ 3, 12,  5, 65],
       [13, 90,  2, 49],
       [35, 79,  1,  8]])

In [3]:
# slice the first 2 row and the first three columns
a2[:2,:3]

array([[ 3, 12,  5],
       [13, 90,  2]])

In [5]:
# slice all the rows and the first column
a2[:,:1]

array([[ 3],
       [13],
       [35]])

In [7]:
# slice all the rows and every other columns
a2[:,::2]

array([[ 3,  5],
       [13,  2],
       [35,  1]])

In [8]:
# using slices to invert the rows and columns
# slice the entire array,but step -1 for both rows and columns
print('Original a2 \n',a2)
print('Inverted as \n', a2[::-1,::-1])

Original a2 
 [[ 3 12  5 65]
 [13 90  2 49]
 [35 79  1  8]]
Inverted as 
 [[ 8  1 79 35]
 [49  2 90 13]
 [65  5 12  3]]
