Arrays present the same problem as lists when you assign an array to another array. If you modify either of the arrays the other array is modified as well. This behaviour occurs as NumPy arrays are mutable objects.  This can be avoided by using the copy() method or np.array(), which will give you a new array that has the same values.

In [3]:
import numpy as np
# ERROR - Copy an array in another array WITHOUT copy()

a2 = np.array([[3, 12, 5, 65],[13, 90, 2, 49], [35, 79, 1, 8]])
print('a2 = \n',a2)

a2Slice = a2[:2,:2]
print('a2Slice = \n', a2Slice)

# what happens if we modified a position of the array?

a2Slice[0,0] = -10
print('\n a2Slice after modification: \n',a2Slice)
print('\n a2 is modified too! = \n',a2)

a2 = 
 [[ 3 12  5 65]
 [13 90  2 49]
 [35 79  1  8]]
a2Slice = 
 [[ 3 12]
 [13 90]]

 a2Slice after modification: 
 [[-10  12]
 [ 13  90]]

 a2 is modified too! = 
 [[-10  12   5  65]
 [ 13  90   2  49]
 [ 35  79   1   8]]


In [13]:
#Copy an array in another array with copy() 

#If you want an independent copy use copy() or np.array
a2 =np.array([[3, 12, 5, 65],[13, 90, 2, 49], [35, 79, 1, 8]])
print('a2 = \n',a2)

a2Slice= a2[:2,:2].copy()
print('\n a2Slice with copy() = \n',a2Slice)

#What happens if we modified a position of the array?
a2Slice[0, 0] = -10
print('\n a2Slice after modified= \n',a2Slice)
print('\n a2 is NOT modified =\n', a2)


a2Slice = np.array(a2[:2,:2])
print('\n a2Slice with np.array() = \n',a2Slice)

#What happens if we modified a position of the array?
a2Slice[0, 0] = -10
print('\n a2Slice after modified= \n',a2Slice)
print('\n a2 is NOT modified =\n', a2)

a2 = 
 [[ 3 12  5 65]
 [13 90  2 49]
 [35 79  1  8]]

 a2Slice with copy() = 
 [[ 3 12]
 [13 90]]

 a2Slice after modified= 
 [[-10  12]
 [ 13  90]]

 a2 is NOT modified =
 [[ 3 12  5 65]
 [13 90  2 49]
 [35 79  1  8]]

 a2Slice with np.array() = 
 [[ 3 12]
 [13 90]]

 a2Slice after modified= 
 [[-10  12]
 [ 13  90]]

 a2 is NOT modified =
 [[ 3 12  5 65]
 [13 90  2 49]
 [35 79  1  8]]
